FROM php:8.2-cli

RUN apt-get update && apt-get install -y --no-install-recommends \
        unzip \
        libsqlite3-dev \
        libssl-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_sqlite

RUN pecl install grpc && docker-php-ext-enable grpc
